import React from "react";
// import MainHeader from "../component/MainHeader";
// import MainCarousel from "../component/MainCarousel";
// import SpecificDomainSection from "../component/SpecificDomainSection";
// import SpecificRegionSection from "../component/SpecificRegionSection";
// import ConsultingSection from "../component/ConsultingSection";
// import PredictionSection from "../component/PredictionSection";
// import LawyerBanner from "../component/LawyerBanner";
// import MainFooter from "../component/MainFooter";
// import SignupForm from "../component/signup/SignupForm";
// import styled from "styled-components";
// import Consulting from "../component/consulting/Consulting";
// import SideBanner from "../component/consulting/SideBanner";
// import Pagination from "../component/common/Pagination";
// import ConsultingDetailQuestion from "../component/consulting/ConsultingDetailQuestion";
// import ConsultingDetailAnswer from "../component/consulting/ConsultingDetailAnswer";
// import PostContainer from "../component/post/PostContainer";
// import Post from "../component/post/Post";
// import styled from "styled-components";
// import PostCarousel from "../component/post/PostCarousel";
// import PostDetailHeader from "../component/post/PostDetailHeader";
// import OtherPosts from "../component/post/OtherPosts";
// import RelatedConsultingQuestions from "../component/post/RelatedConsultingQuestions";
// import PostDetailLawyerInfo from "../component/post/PostDetailLawyerInfo";
// import Video from "../component/video/Video";
// import VideoDetailHeader from "../component/video/VideoDetailHeader";
// import VideoDetailContent from "../component/video/VideoDetailContent";
// import PremiumLawyer from "../component/lawyer/PremiumLawyer";
// import NormalLawyer from "../component/lawyer/NormalLawyer";
// import LawyerFilter from "../component/lawyer/LawyerFilter";
// import IntegratePost from "../component/post/IntegratePost";
// import IntegrateCarousel from "../component/common/IntegrateCarousel";
// import IntegrateCarouselItem from "../component/integrate/IntegrateCarouselItem";
// import LawyerDetailHeader from "../component/lawyer/LawyerDetailHeader";
import LawyerDetailInfo from "../component/lawyer/LawyerDetailInfo";

const TestPage = (props) => {
  return <LawyerDetailInfo />;
};

export default TestPage;
